#!/bin/bash

set -ex

# move back to the root context
cd ..
pwd

docker build \
    --build-arg APP_COMMIT=$SOURCE_COMMIT \
    --build-arg APP_VERSION=$CACHE_TAG \
    -f $DOCKERFILE_PATH -t $IMAGE_NAME .
